### ISSUE TITLE
Can drop die into cup without looking and still call no mames

### ISSUE THREAD

**Issue by topace14** [franc0is/nomames#47]
I'm not sure if this is actually a problem, since you still don't know what what under the cup, but maybe if the cup isn't visible it shouldn't be an active drop zone?

**Comment by rajkk1** [comment]
Oh yeah, I'm happy to work on this! I think a fix would be to disable the no mames button if at least a single die is rolled. How does that sound?

**Comment by rajkk1** [comment]
Oh wait this looks like it's been solved?
