### ISSUE TITLE
Set the direction of the 'pass' arrow to what it was the previous round

### ISSUE THREAD

**Issue by santgr** [franc0is/nomames#52]
Currently the pass arrow reverts back to the original '>' setting after each round. Last night Felipe accidentally sent it the wrong way because he thought the arrow direction carried over from one round to the next. I think it would be more intuitive that way.

**Comment by topace14** [comment]
I agree that the current set-up doesn't necessarily make sense, but I'm not sure this solves the issue. I think a pop up when you first click pass, that asks "would you like to pass it to (player name to your left) or (player name to your right)" and having their names be buttons.

**Comment by santgr** [comment]
That sounds like a great alternative!
